/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.gestao.venda.view.tela;

/**
 *
 * @author Daniel Rodrigues
 */
public class JanelaAbrir extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaAbrir
     */
    public JanelaAbrir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnRadioCafe = new javax.swing.JRadioButton();
        btnRadioCha = new javax.swing.JRadioButton();
        btnVerificar = new javax.swing.JButton();
        txtLabel = new javax.swing.JLabel();

        buttonGroup1.add(btnRadioCafe);
        btnRadioCafe.setText("Café");

        buttonGroup1.add(btnRadioCha);
        btnRadioCha.setText("Chá");

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        txtLabel.setText("Sem nenhuma verificação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnRadioCafe)
                        .addGap(44, 44, 44)
                        .addComponent(btnRadioCha)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerificar)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioCafe)
                    .addComponent(btnRadioCha))
                .addGap(37, 37, 37)
                .addComponent(btnVerificar)
                .addGap(18, 18, 18)
                .addComponent(txtLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        if(btnRadioCafe.isSelected()){
            txtLabel.setText("Café selecionado!");
        }
        if(btnRadioCha.isSelected()){
            txtLabel.setText("Chá selecionado!");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnRadioCafe;
    private javax.swing.JRadioButton btnRadioCha;
    private javax.swing.JButton btnVerificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel txtLabel;
    // End of variables declaration//GEN-END:variables
}
